language: "en-US"
reviews:
  collapse_walkthrough: true
  sequence_diagrams: false
  tools:
    # Disable eslint and markdown lint since they are handled separately
    # by the ci.yaml workflow, and coderabbit doesn't know how to eslint
    # nextjs projects.
    eslint:
      enabled: false
    markdownlint:
      enabled: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!src/components/ui/**"
    - "!src/hooks/**"
  path_instructions:
    - path: "src/data/*clues.ts"
      instructions: |
        Review all clues and ensure that:
          - Clues have appropriate ending punctuation (period or question mark, depending on type of clue).
          - Clues that ask a question have an answer specified.
          - Clues that ask for a photo or a selfie are marked with the IMAGE answerType.
          - Clues that have an answer specified are marked with the TEXT answerType.
          - Grammar and spelling is correct.
          - Clues have a consistent phrasing and style.
    - path: "**/*.tsx"
      instructions: |
        Review all TypeScript files and ensure that:
          - Components have appropriate accessibility attributes on them.
          - All headings are in sentence, not title, case.
          - Table headers are in sentence case.
    - path: "**/*.md"
      instructions: |
        Review all markdown files and ensure that:
          - All headings are in sentence, not title, case.
          - All list sentences end in a period.
          - Spelling and grammar is correct.
          - Table headers are in sentence case.
