language: "en-US"
reviews:
  collapse_walkthrough: true
  sequence_diagrams: false
  tools:
    # Disable eslint and markdown lint since they are handled separately
    # by the ci.yaml workflow, and coderabbit doesn't know how to eslint
    # nextjs projects.
    eslint:
      enabled: false
    markdownlint:
      enabled: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!src/components/ui/**"
    - "!src/hooks/**"
  path_instructions:
    - path: "src/data/*clues.ts"
      instructions: |
        Review all clues and ensure that:
          - Clues have corresponding text in the messages/*.json files.
          - Clues that ask a question have an answer specified.
          - Clues that ask for a photo or a selfie are marked with the IMAGE answerType.
          - Clues that have an answer specified are marked with the TEXT answerType.
          - Clues with the IMAGE clueType have a jpg file in public/clue-images folder with the same name as the clue's id.
          - Clues with the IMAGE answerType have an expectedImageCount specified.
    - path: "**/*.tsx"
      instructions: |
        Review all TypeScript files and ensure that:
          - No UI strings are hardcoded.
          - Components have appropriate accessibility attributes on them.
          - All headings are in sentence, not title, case.
          - Table headers are in sentence case.
    - path: "**/*.md"
      instructions: |
        Review all markdown files and ensure that:
          - All headings are in sentence, not title, case.
          - All list sentences end in a period.
          - Spelling and grammar is correct.
          - Table headers are in sentence case.
