name: Deploy - prod

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ vars.APP_BASE_URL }}
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare
        uses: ./.github/actions/cloudflare-deploy
        with:
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          deploy_env: ${{ vars.DEPLOY_ENV }}
          flightaware_api_key: ${{ secrets.FLIGHTAWARE_API_KEY }}
          kinde_client_id: ${{ secrets.KINDE_CLIENT_ID }}
          kinde_client_secret: ${{ secrets.KINDE_CLIENT_SECRET }}
          kinde_issuer_url: ${{ vars.KINDE_ISSUER_URL }}
          kinde_post_login_redirect_url: ${{ vars.KINDE_POST_LOGIN_REDIRECT_URL }}
          kinde_post_logout_redirect_url: ${{ vars.KINDE_POST_LOGOUT_REDIRECT_URL }}
          kinde_site_url: ${{ vars.KINDE_SITE_URL }}
