name: CI

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  label:
    name: Require label
    runs-on: ubuntu-latest

    steps:
      - name: Verify labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          add_comment: true
          labels: |
            breaking change
            ignore-for-release-notes
            feature
            enhancement
            bug
            documentation
            development
            dependencies
            DevOps
